name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: "git hub action"
        run: pwd

      - name: 'testing github'
        run: echo youssef

      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u yousseframadan676 --password dckr_pat_1oAouIE_QMTZYDsm8X3tSzDC-nU
